### ISSUE TITLE
Client side usage of the library

### ISSUE THREAD

**Issue by AaronPorts** [airgram/airgram#14] opened 2019-01-11 21:01 UTC
As mtproto supports http, can I use this library direct on the client side without node?

**Comment by airgram** [comment] 2019-01-14 06:38
Unfortunately not. 
Airgram uses some NodeJS features. Browsers support might be added in the future.

**Comment by airgram** [comment] 2019-01-14 06:39
Duplicate of #1

**Closed by airgram** 2019-01-14 06:39 UTC
